package knowledge

import (
	"context"
	"testing"
)

// TestRetrieverPopSupplement6BRecall guards the 2026-09-26 科普补充第六批(方向B):
// home-environment questions (室内装修与油烟、空调与军团菌、尘螨蟑螂、驱蚊产品、
// 清洁剂混用与家庭消毒、饮水与二次供水、基站辐射、一氧化碳中毒现场处置、教室照明).
// Same convention as direction A: a SHORT topical condition_zh earns the
// containment bonus, so the gate asserts plain colloquial phrasing reaches top5.
func TestRetrieverPopSupplement6BRecall(t *testing.T) {
	r := NewRetriever(newTestStore(t))
	cases := map[string]string{
		// 室内空气污染与通风
		"室内空气污染有哪些来源":   "he-indoor-air-pollution",
		"家里空气不好会不会得肺癌":  "he-indoor-air-pollution",
		"室内污染物分哪几类":     "he-indoor-air-pollution",
		"房间不通风对身体有什么影响": "he-indoor-air-pollution",
		"一天开窗几次比较好":     "he-ventilation",
		"每次通风多长时间合适":    "he-ventilation",
		"房间里闷头晕是不是缺氧":   "he-ventilation",
		"室内二氧化碳浓度多少算高":  "he-ventilation",
		"雾霾天要不要开窗通风":    "he-ventilation",
		"开空调需要开窗吗":      "he-ventilation",
		"新风系统能代替开窗吗":    "he-ventilation",
		// 装修污染
		"装修完多久能入住":   "he-renovation-pollution",
		"新房甲醛多少算超标":  "he-renovation-pollution",
		"装修后眼睛流泪嗓子疼": "he-renovation-pollution",
		"除甲醛有没有用":    "he-renovation-pollution",
		"豪华装修污染更重吗":  "he-renovation-pollution",
		"花岗岩氡气超标标准":  "he-renovation-pollution",
		"装修异味越大越有毒吗": "he-renovation-pollution",
		// 厨房油烟
		"厨房油烟会致癌吗":      "he-oil-fume-harm",
		"不抽烟的女性为什么也得肺癌": "he-oil-fume-harm",
		"油烟里有多少种化学成分":   "he-oil-fume-harm",
		"长期做饭容易得慢支吗":    "he-oil-fume-harm",
		"一小时油烟相当于几支烟":   "he-oil-fume-harm",
		"炒菜油温多少度比较合适":   "he-oil-fume-prevention",
		"油烟机什么时候开最有效":   "he-oil-fume-prevention",
		"油烟机装多高合适":      "he-oil-fume-prevention",
		"怎么做饭油烟少一些":     "he-oil-fume-prevention",
		"爆炒用哪种油好":       "he-oil-fume-prevention",
		"油锅冒烟了还能下菜吗":    "he-oil-fume-prevention",
		// 军团菌
		"军团菌是什么":        "he-legionella",
		"军团菌肺炎严重吗":      "he-legionella",
		"军团菌会人传人吗":      "he-legionella",
		"军团菌潜伏期几天":      "he-legionella",
		"空调制冷塔传播军团菌":    "he-legionella",
		"军团菌用什么抗生素":     "he-legionella",
		"肺炎总是治不好要查军团菌吗": "he-legionella",
		"军团病有疫苗吗":       "he-legionella",
		"军团菌病高发人群":      "he-legionella",
		"加湿器会长军团菌吗":     "he-legionella-water-prevention",
		"加湿器该加什么水":      "he-legionella-water-prevention",
		"中央空调检出军团菌怎么办":  "he-legionella-water-prevention",
		"冷却塔要多久清洗消毒一次":  "he-legionella-water-prevention",
		"热水器多少度能抑制军团菌":  "he-legionella-water-prevention",
		"按摩浴缸军团菌风险":     "he-legionella-water-prevention",
		// 空调清洗与使用
		"空调不洗直接开有害吗":    "he-air-conditioner-cleaning",
		"空调滤网怎么自己清洗":    "he-air-conditioner-cleaning",
		"空调有霉味怎么处理":     "he-air-conditioner-cleaning",
		"空调散热片要用清洁剂泡多久": "he-air-conditioner-cleaning",
		"空调菌落总数超标多少倍":   "he-air-conditioner-cleaning",
		"夏天空调开机前要清洗吗":   "he-air-conditioner-cleaning",
		"空调清洗服务要看哪些项目":  "he-air-conditioner-cleaning",
		"夏天空调开到几度最健康":   "he-air-conditioner-usage",
		"室内外温差别超过多少度":   "he-air-conditioner-usage",
		"空调房喉咙干放盆水有用吗":  "he-air-conditioner-usage",
		"除湿模式和制冷怎么选":    "he-air-conditioner-usage",
		"整晚开空调第二天头疼":    "he-air-conditioner-usage",
		"老人小孩开空调要注意什么":  "he-air-conditioner-usage",
		// 冰箱与李斯特菌
		"冰箱里的细菌叫什么":     "he-fridge-listeria",
		"李斯特菌致死率高吗":     "he-fridge-listeria",
		"孕妇能吃冰箱拿出来的熟食吗": "he-fridge-listeria",
		"凉拌菜和预切果盘的风险":   "he-fridge-listeria",
		"李斯特菌在冰箱里能繁殖吗":  "he-fridge-listeria",
		"剩菜加热到多少度才安全":   "he-fridge-listeria",
		"李斯特菌多久会发病":     "he-fridge-listeria",
		// 尘螨
		"尘螨过敏会引起哮喘吗":     "he-dust-mites",
		"床褥里螨虫有多少":       "he-dust-mites",
		"凉席放一年螨虫多吗":      "he-dust-mites",
		"螨虫喜欢什么温度和湿度":    "he-dust-mites",
		"孩子几岁容易得螨性哮喘":    "he-dust-mites",
		"肘窝腘窝湿疹是螨虫过敏吗":   "he-dust-mites",
		"被子晒过还拍不拍":       "he-mite-control",
		"多少度热水洗床单能杀死螨虫":  "he-mite-control",
		"毛绒玩具放冰箱冷冻除螨可以吗": "he-mite-control",
		"室内湿度多少能抑制螨虫繁殖":  "he-mite-control",
		"除螨仪到底有没有效果":     "he-mite-control",
		"晒被子就能除螨吗":       "he-mite-control",
		"床垫用什么吸尘器除螨":     "he-mite-control",
		// 蟑螂
		"家里有蟑螂怎么消灭":    "he-cockroach",
		"德国小蠊和美洲大蠊的区别": "he-cockroach",
		"蟑螂会引起哮喘过敏吗":   "he-cockroach",
		"踩死蟑螂卵还能孵化吗":   "he-cockroach",
		"灭蟑药多久用一次":     "he-cockroach",
		"蟑螂药和毒饵哪种好":    "he-cockroach",
		"楼上蟑螂爬进厨房怎么办":  "he-cockroach",
		"蟑螂钻进耳朵了要就医吗":  "he-cockroach",
		// 防蚊灭蚊产品
		"防蚊产品怎么选":         "he-mosquito-repellent-products",
		"灭蚊灯真的能灭蚊吗":       "he-mosquito-repellent-products",
		"电热蚊香液孕妇能用吗":      "he-mosquito-repellent-products",
		"杀虫气雾剂用完要通风多久":    "he-mosquito-repellent-products",
		"驱蚊手环管用吗":         "he-mosquito-repellent-products",
		"超声波驱蚊器有没有科学依据":   "he-mosquito-repellent-products",
		"买驱蚊产品要看什么证号":     "he-mosquito-repellent-products",
		"柠檬桉油驱蚊喷雾两岁以下能用吗": "he-mosquito-repellent-products",
		"纯植物无农药驱蚊可信吗":     "he-mosquito-repellent-products",
		"避蚊胺浓度多少给儿童用":     "he-repellent-ingredients-children",
		"驱蚊酯几个月宝宝能用":      "he-repellent-ingredients-children",
		"派卡瑞丁孕妇安全吗":       "he-repellent-ingredients-children",
		"户外防蚊选哪种成分":       "he-repellent-ingredients-children",
		"给小孩涂驱蚊液要注意什么":    "he-repellent-ingredients-children",
		// 清洁剂混用
		"洁厕灵和84消毒液能一起用吗": "he-cleaner-mixing",
		"混用清洁剂产生的毒气叫什么":  "he-cleaner-mixing",
		"84消毒液能倒进洗衣液吗":   "he-cleaner-mixing",
		"漂白剂加玻璃清洁剂会中毒吗":  "he-cleaner-mixing",
		"大扫除清洁剂要戴护目镜吗":   "he-cleaner-mixing",
		"清理霉菌能把消毒剂混着用吗":  "he-cleaner-mixing",
		"吸入氯气呼吸困难怎么急救":   "he-cleaner-mixing",
		"洁厕灵进了眼睛要冲多久":    "he-cleaner-mixing",
		// 家庭消毒
		"消毒用酒精是不是浓度越高越好":  "he-alcohol-disinfection",
		"能在屋里喷酒精消毒吗":      "he-alcohol-disinfection",
		"75%酒精擦什么":        "he-alcohol-disinfection",
		"家里该存多少酒精才安全":     "he-alcohol-disinfection",
		"免洗洗手液用多了皮肤干":     "he-alcohol-disinfection",
		"酒精喷衣服遇到明火会爆炸吗":   "he-alcohol-disinfection",
		"84消毒液怎么稀释成多少浓度":  "he-chlorine-bleach-dilution",
		"84消毒液有效氯含量是多少":   "he-chlorine-bleach-dilution",
		"物体表面消毒用什么含氯浓度":   "he-chlorine-bleach-dilution",
		"消毒片用热水化开行吗":      "he-chlorine-bleach-dilution",
		"消毒液浓度太高嗓子疼胸闷":    "he-chlorine-bleach-dilution",
		"消毒后要再用清水擦一遍吗":    "he-chlorine-bleach-dilution",
		"哪些情况一定要洗手":       "he-handwashing",
		"摸过电梯按钮要不要洗手":     "he-handwashing",
		"七步洗手法具体是哪七步":     "he-handwashing",
		"洗手至少要搓多少秒":       "he-handwashing",
		"什么时候免洗洗手液不能代替水洗": "he-handwashing",
		"接完外卖接触钱币后要洗手吗":   "he-handwashing",
		"普通湿巾和消毒湿巾有什么区别":  "he-disinfecting-wipes",
		"消毒湿巾能擦手机和门把手吗":   "he-disinfecting-wipes",
		"卫生湿巾是抑菌还是消毒":     "he-disinfecting-wipes",
		"消毒湿巾能擦嘴巴和眼睛吗":    "he-disinfecting-wipes",
		"苯扎氯铵湿巾算消毒吗":      "he-disinfecting-wipes",
		"湿巾擦完马上擦干算消毒吗":    "he-disinfecting-wipes",
		"家里需要天天消毒吗":       "he-home-disinfection-basics",
		"消毒剂能喷到黏膜上吗":      "he-home-disinfection-basics",
		"室外环境需要消毒吗":       "he-home-disinfection-basics",
		"向空气喷消毒液有用吗":      "he-home-disinfection-basics",
		"过度消毒会不会伤呼吸道":     "he-home-disinfection-basics",
		"紫外线消毒灯使用时屋里能有人吗": "he-ultraviolet-lamp",
		"紫外线灯照多久合适":       "he-ultraviolet-lamp",
		"紫外线灯会伤眼睛得白内障吗":   "he-ultraviolet-lamp",
		"忘了关掉紫外线灯在里面待了很久": "he-ultraviolet-lamp",
		"消毒灯有臭氧要通风吗":      "he-ultraviolet-lamp",
		"家里墙壁长霉点怎么办":      "he-household-mold",
		"被水泡过的地毯还能用吗":     "he-household-mold",
		"洪水过后房间发霉怎么清理":    "he-household-mold",
		"刷漆能盖住墙上的霉菌吗":     "he-household-mold",
		"除霉菌要戴什么口罩和手套":    "he-household-mold",
		"哪些人不能参与清除霉菌":     "he-household-mold",
		"家里湿度多少不容易长霉":     "he-household-mold",
		// 饮用水
		"生活饮用水新标准什么时候实施":     "he-drinking-water-standard",
		"新版饮用水标准有多少项指标":      "he-drinking-water-standard",
		"饮用水指标为什么从106项改成97项": "he-drinking-water-standard",
		"出厂水游离氯限值变严了吗":       "he-drinking-water-standard",
		"城乡饮用水标准统一了吗":        "he-drinking-water-standard",
		"自来水必须烧开才能喝吗":        "he-tap-water-practice",
		"水垢很多的水能喝吗":          "he-tap-water-practice",
		"净水器滤芯多久换一次":         "he-tap-water-practice",
		"RO反渗透和超滤选哪个":        "he-tap-water-practice",
		"刚放的水发白静置就清了":        "he-tap-water-practice",
		"小区管道老旧水会二次污染吗":      "he-tap-water-practice",
		"喝纯净水会缺钙吗":           "he-water-myths",
		"千滚水和隔夜水能不能喝":        "he-water-myths",
		"阴阳水拉肚子是怎么回事":        "he-water-myths",
		"必须每天喝够八杯水吗":         "he-water-myths",
		"碱性水能改变酸性体质吗":        "he-water-myths",
		"喝水太多会水中毒吗":          "he-water-myths",
		"一天大概喝多少水合适":         "he-daily-water-intake",
		"看尿液颜色知道缺不缺水":        "he-daily-water-intake",
		"哺乳期要多喝多少水":          "he-daily-water-intake",
		"心衰肾病的人为什么要限水":       "he-daily-water-intake",
		"运动后怎么补水才合适":         "he-daily-water-intake",
		"老人不觉得口渴要不要喝水":       "he-daily-water-intake",
		"农村自家打的井水安全吗":        "he-rural-drinking-water",
		"集中供水工程和分散供水的区别":     "he-rural-drinking-water",
		"山泉水烧开了能喝吗":          "he-rural-drinking-water",
		"村里间歇供水怎么储水":         "he-rural-drinking-water",
		"长期停水水管里的水要放掉吗":      "he-rural-drinking-water",
		"小区楼顶水箱多久清洗一次":       "he-secondary-water-supply",
		"自来水里有红虫是什么原因":       "he-secondary-water-supply",
		"二次供水需要加盖加锁吗":        "he-secondary-water-supply",
		"停水后来水很浑能直接用吗":       "he-secondary-water-supply",
		"水箱清洗人员要健康证吗":        "he-secondary-water-supply",
		"二次供水水质多久检验一次":       "he-secondary-water-supply",
		"水有油漆味是不是水箱污染":       "he-secondary-water-supply",
		"家里的储水罐要加盖吗":         "he-laundry-water-safety",
		"桶装水开封后几天内喝完":        "he-laundry-water-safety",
		"饮水机内部多久清洗一次":        "he-laundry-water-safety",
		"水缸长青苔还能储饮用水吗":       "he-laundry-water-safety",
		"蚊子会在储水容器里产卵吗":       "he-laundry-water-safety",
		// 饮水风险背景
		"全球有多少人喝受粪便污染的水":  "he-who-drinking-water",
		"喝生水会得哪些传染病":      "he-who-drinking-water",
		"饮用水里最主要的化学风险是什么": "he-who-drinking-water",
		"自来水里的铅从哪来":       "he-who-drinking-water",
		"什么是安全管理的饮用水服务":   "he-who-drinking-water",
		"水安全计划是什么":        "he-who-drinking-water",
		"微塑料和PFAS对饮用水的影响": "he-who-drinking-water",
		// 辐射
		"小区里建基站辐射安全吗":  "he-emf-base-station",
		"电磁辐射的国标限值是多少": "he-emf-base-station",
		"5G基站辐射比吹风机大吗": "he-emf-base-station",
		"提速是不是靠加大基站功率": "he-emf-base-station",
		"防辐射贴和防辐射服有用吗": "he-emf-base-station",
		"基站多手机辐射反而小吗":  "he-emf-base-station",
		"通信辐射会不会损伤DNA": "he-emf-base-station",
		// 一氧化碳
		"一氧化碳中毒怎么现场急救":   "he-carbon-monoxide-first-aid",
		"碳氧血红蛋白多少算中度中毒":  "he-carbon-monoxide-first-aid",
		"一氧化碳中毒要做高压氧吗":   "he-carbon-monoxide-first-aid",
		"中毒醒过来后又变傻是怎么回事": "he-carbon-monoxide-first-aid",
		"一氧化碳中毒为什么察觉不到":  "he-carbon-monoxide-first-aid",
		"车里开暖气睡觉一氧化碳中毒":  "he-carbon-monoxide-first-aid",
		"救一氧化碳中毒的人要先戴什么": "he-carbon-monoxide-first-aid",
		"家里要不要装CO报警器":    "he-carbon-monoxide-first-aid",
		// 教室照明
		"教室照明新标准什么时候实施":  "he-classroom-lighting",
		"教室灯要有防蓝光等级吗":    "he-classroom-lighting",
		"课桌上面的灯要装多高":     "he-classroom-lighting",
		"教室采光应该从哪一侧照进来":  "he-classroom-lighting",
		"新建教室冬至日照要几小时":   "he-classroom-lighting",
		"教室灯频闪标准是多少":     "he-classroom-lighting",
		"培训机构也要按教室照明标准吗": "he-classroom-lighting",
		"黑板要不要单独装灯":      "he-classroom-lighting",
	}
	for query, want := range cases {
		res, err := r.Retrieve(context.Background(), query, 5)
		if err != nil {
			t.Fatalf("检索失败: %v", err)
		}
		found := false
		for _, rr := range res {
			if rr.Entry.ID == want {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("查询 %q: 期望 top5 含 %s，实际 %v", query, want, entryIDs(res))
		}
	}
}
