package knowledge

import (
	"context"
	"sort"
	"strings"
)

// minEMLScore is the minimum score for an EML entry to be returned.
const minEMLScore = 1.0

// emlZhAliases maps common Chinese drug names to their WHO EML INN entries so
// Chinese-speaking users can look up the EML without knowing the English INN.
var emlZhAliases = map[string]string{
	"阿莫西林":        "amoxicillin",
	"阿莫西林克拉维酸":   "amoxicillin + clavulanic acid",
	"阿司匹林":        "acetylsalicylic acid",
	"布洛芬":         "ibuprofen",
	"对乙酰氨基酚":     "paracetamol (acetaminophen)",
	"扑热息痛":        "paracetamol (acetaminophen)",
	"二甲双胍":        "metformin",
	"头孢噻肟":        "cefotaxime",
	"头孢曲松":        "ceftriaxone",
	"头孢氨苄":        "cephalexin",
	"头孢唑林":        "cefazolin",
	"美罗培南":        "meropenem",
	"吗啡":          "morphine",
	"肾上腺素":        "epinephrine (adrenaline)",
	"沙丁胺醇":        "salbutamol",
	"泼尼松龙":        "prednisolone",
	"地塞米松":        "dexamethasone",
	"奥司他韦":        "oseltamivir",
	"阿奇霉素":        "azithromycin",
	"青霉素":         "benzylpenicillin",
	"氨苄西林":        "ampicillin",
	"万古霉素":        "vancomycin",
	"华法林":         "warfarin",
	"氯吡格雷":        "clopidogrel",
	"辛伐他汀":        "simvastatin",
	"氨氯地平":        "amlodipine",
	"缬沙坦":         "valsartan",
	"呋塞米":         "furosemide",
	"氢氯噻嗪":        "hydrochlorothiazide",
	"螺内酯":         "spironolactone",
	"左甲状腺素":       "levothyroxine",
	"奥美拉唑":        "omeprazole",
	"甲硝唑":         "metronidazole",
	"多西环素":        "doxycycline",
	"克拉霉素":        "clarithromycin",
	"庆大霉素":        "gentamicin",
	"链霉素":         "streptomycin",
	"异烟肼":         "isoniazid",
	"利福平":         "rifampicin",
	"乙胺丁醇":        "ethambutol",
	"吡嗪酰胺":        "pyrazinamide",
	"氯喹":          "chloroquine",
	"苯巴比妥":        "phenobarbital",
	"苯妥英":         "phenytoin",
	"卡马西平":        "carbamazepine",
	"丙戊酸":         "valproic acid (sodium valproate)",
	"地西泮":         "diazepam",
	"氟西汀":         "fluoxetine",
	"舍曲林":         "sertraline",
	"氯氮平":         "clozapine",
	"利培酮":         "risperidone",
	"美托洛尔":        "metoprolol",
	"阿替洛尔":        "atenolol",
	"地高辛":         "digoxin",
	"硝苯地平":        "nifedipine",
	"硝酸甘油":        "glyceryl trinitrate",
	"肝素":          "heparin",
	"苯海拉明":        "diphenhydramine",
	"氯雷他定":        "loratadine",
	"西替利嗪":        "cetirizine",
	"奥氮平":         "olanzapine",
	"喹硫平":         "quetiapine",
	"阿托品":         "atropine",
	"纳洛酮":         "naloxone",
	"维生素B1":       "thiamine",
	"维生素C":        "ascorbic acid",
	"叶酸":          "folic acid",
	"葡萄糖":         "glucose",
	"氯化钾":         "potassium chloride",
	"碳酸氢钠":        "sodium bicarbonate",
	"硫酸镁":         "magnesium sulfate",
	"多巴胺":         "dopamine",
	"多巴酚丁胺":       "dobutamine",
	"去甲肾上腺素":      "norepinephrine",
	"胰岛素":         "insulin",
	"格列本脲":        "glibenclamide",
	"格列齐特":        "gliclazide",
	"吡格列酮":        "pioglitazone",
	"阿卡波糖":        "acarbose",
	"别嘌醇":         "allopurinol",
	"秋水仙碱":        "colchicine",
	"泼尼松":         "prednisolone",
	"羟氯喹":         "hydroxychloroquine",
	"甲氨蝶呤":        "methotrexate",
	"柳氮磺吡啶":       "sulfasalazine",
	"雷尼替丁":        "ranitidine",
	"西咪替丁":        "cimetidine",
	"碳酸锂":         "lithium carbonate",
	"丙戊酸钠":        "valproic acid (sodium valproate)",
	"苯妥英钠":        "phenytoin",
	"氯丙嗪":         "chlorpromazine",
	"氟哌啶醇":        "haloperidol",
	"曲唑酮":         "trazodone",
	"阿米替林":        "amitriptyline",
	"多塞平":         "doxepin",
	"丙米嗪":         "imipramine",
	"赛庚啶":         "cyproheptadine",
	"特非那定":        "terfenadine",
	"布地奈德":        "budesonide",
	"氟替卡松":        "fluticasone",
	"沙美特罗":        "salmeterol",
	"福莫特罗":        "formoterol",
	"异丙托溴铵":       "ipratropium bromide",
	"噻托溴铵":        "tiotropium",
	"茶碱":          "theophylline",
	"氨茶碱":         "aminophylline",
	"坦索罗辛":        "tamsulosin",
	"特拉唑嗪":        "terazosin",
	"多沙唑嗪":        "doxazosin",
	"卡托普利":        "captopril",
	"依那普利":        "enalapril",
	"培哚普利":        "perindopril",
	"氯沙坦":         "losartan",
	"厄贝沙坦":        "irbesartan",
	"比索洛尔":        "bisoprolol",
	"卡维地洛":        "carvedilol",
	"维拉帕米":        "verapamil",
	"地尔硫卓":        "diltiazem",
	"胺碘酮":         "amiodarone",
	"利多卡因":        "lidocaine",
	"普鲁卡因":        "procaine",
	"布比卡因":        "bupivacaine",
	"罗哌卡因":        "ropivacaine",
	"左氧氟沙星":       "levofloxacin",
	"环丙沙星":        "ciprofloxacin",
	"诺氟沙星":        "norfloxacin",
	"氧氟沙星":        "ofloxacin",
	"四环素":         "tetracycline",
	"米诺环素":        "minocycline",
	"磺胺甲噁唑":       "sulfamethoxazole + trimethoprim",
	"复方新诺明":       "sulfamethoxazole + trimethoprim",
	"呋喃妥因":        "nitrofurantoin",
	"两性霉素B":       "amphotericin B",
	"制霉菌素":        "nystatin",
	"克霉唑":         "clotrimazole",
	"咪康唑":         "miconazole",
	"酮康唑":         "ketoconazole",
	"氟康唑":         "fluconazole",
	"伊曲康唑":        "itraconazole",
	"伏立康唑":        "voriconazole",
	"特比萘芬":        "terbinafine",
	"阿昔洛韦":        "aciclovir",
	"伐昔洛韦":        "valaciclovir",
	"更昔洛韦":        "ganciclovir",
	"齐多夫定":        "zidovudine",
	"拉米夫定":        "lamivudine",
	"恩替卡韦":        "entecavir",
	"替诺福韦":        "tenofovir disoproxil fumarate",
	"利巴韦林":        "ribavirin",
	"金刚烷胺":        "amantadine",
	"阿苯达唑":        "albendazole",
	"甲苯达唑":        "mebendazole",
	"吡喹酮":         "praziquantel",
	"伊维菌素":        "ivermectin",
	"氯硝柳胺":        "niclosamide",
	"青蒿琥酯":        "artesunate",
	"青蒿素":         "artemisinin",
	"伯氨喹":         "primaquine",
	"乙胺嘧啶":        "pyrimethamine",
	"多黏菌素B":       "polymyxin B",
	"黏菌素":         "colistin",
	"阿米卡星":        "amikacin",
	"妥布霉素":        "tobramycin",
	"红霉素":         "erythromycin",
	"罗红霉素":        "roxithromycin",
	"林可霉素":        "lincomycin",
	"克林霉素":        "clindamycin",
	"替考拉宁":        "teicoplanin",
	"利奈唑胺":        "linezolid",
	"左旋多巴":        "levodopa + carbidopa",
	"卡比多巴":        "levodopa + carbidopa",
	"普拉克索":        "pramipexole",
	"罗匹尼罗":        "ropinirole",
	"苯海索":         "trihexyphenidyl",
	"加巴喷丁":        "gabapentin",
	"普瑞巴林":        "pregabalin",
	"拉莫三嗪":        "lamotrigine",
	"托吡酯":         "topiramate",
	"左乙拉西坦":       "levetiracetam",
	"丙泊酚":         "propofol",
	"氯胺酮":         "ketamine",
	"七氟烷":         "sevoflurane",
	"异氟烷":         "isoflurane",
	"氧化亚氮":        "nitrous oxide",
	"依托咪酯":        "etomidate",
	"咪达唑仑":        "midazolam",
	"曲马多":         "tramadol",
	"可待因":         "codeine",
	"芬太尼":         "fentanyl",
	"美沙酮":         "methadone",
	"羟考酮":         "oxycodone",
	"氢吗啡酮":        "hydromorphone",
	"丁丙诺啡":        "buprenorphine",
	"塞来昔布":        "celecoxib",
	"美洛昔康":        "meloxicam",
	"吲哚美辛":        "indometacin",
	"萘普生":         "naproxen",
	"双氯芬酸":        "diclofenac",
	"洛哌丁胺":        "loperamide",
	"昂丹司琼":        "ondansetron",
	"甲氧氯普胺":       "metoclopramide",
	"乳果糖":         "lactulose",
	"比沙可啶":        "bisacodyl",
	"甘油":          "glycerol",
	"多库酯":         "docusate sodium",
	"山莨菪碱":        "hyoscine butylbromide",
	"丁溴东莨菪碱":      "hyoscine butylbromide",
	"氨溴索":         "ambroxol",
	"乙酰半胱氨酸":      "acetylcysteine",
	"孟鲁司特":        "montelukast",
	"扎鲁司特":        "zafirlukast",
	"西地那非":        "sildenafil",
	"他达拉非":        "tadalafil",
	"非那雄胺":        "finasteride",
	"多奈哌齐":        "donepezil",
	"美金刚":         "memantine",
	"卡巴拉汀":        "rivastigmine",
	"帕罗西汀":        "paroxetine",
	"艾司西酞普兰":      "escitalopram",
	"文拉法辛":        "venlafaxine",
	"度洛西汀":        "duloxetine",
	"米氮平":         "mirtazapine",
	"阿普唑仑":        "alprazolam",
	"艾司唑仑":        "estazolam",
	"佐匹克隆":        "zopiclone",
	"唑吡坦":         "zolpidem",
	"褪黑素":         "melatonin",
	"苯扎贝特":        "bezafibrate",
	"非诺贝特":        "fenofibrate",
	"吉非罗齐":        "gemfibrozil",
	"依折麦布":        "ezetimibe",
	"瑞舒伐他汀":       "rosuvastatin",
	"阿托伐他汀":       "atorvastatin",
	"普伐他汀":        "pravastatin",
	"氟伐他汀":        "fluvastatin",
	"洛伐他汀":        "lovastatin",
	"维生素D":        "ergocalciferol",
	"维生素D3":       "colecalciferol",
	"维生素K1":       "phytomenadione",
	"维生素B12":      "cyanocobalamin",
	"烟酸":          "nicotinic acid",
	"核黄素":         "riboflavin",
	"钙剂":          "calcium",
	"锌":           "zinc sulfate",
	"铁剂":          "ferrous salt",
	"硫酸亚铁":        "ferrous salt",
	"碳酸钙":         "calcium carbonate",
	"氯化钠":         "sodium chloride",
	"生理盐水":        "sodium chloride",
	"乳酸钠林格":       "sodium lactate",
	"右旋糖酐":        "dextran",
	"白蛋白":         "albumin",
	"免疫球蛋白":       "immunoglobulin",
	"破伤风抗毒素":      "tetanus antitoxin",
	"肉毒毒素":        "botulinum toxin",
	"碘":           "iodine",
	"聚维酮碘":        "povidone iodine",
	"过氧化氢":        "hydrogen peroxide",
	"高锰酸钾":        "potassium permanganate",
	"酒精":          "ethanol",
	"甘油三酯":        "glycerol",
}

// RetrieveEMLDrug looks up medicines in the WHO EML by English INN (exact /
// substring) or by common Chinese drug name (via the alias table).
func (r *KeywordRetriever) RetrieveEMLDrug(ctx context.Context, query string, topK int) ([]EMLResult, error) {
	if topK <= 0 {
		topK = 10
	}
	query = strings.TrimSpace(query)
	if query == "" {
		return nil, nil
	}
	qLower := strings.ToLower(query)
	// Chinese query -> map to the INN entry first.
	if alias, ok := emlZhAliases[query]; ok {
		qLower = strings.ToLower(alias)
	}

	var results []EMLResult
	for i := range r.store.EMLEntries {
		e := &r.store.EMLEntries[i]
		nameLower := strings.ToLower(e.Name)
		score, ok := 0.0, false
		switch {
		case nameLower == qLower:
			score, ok = 12, true // exact INN
		case strings.Contains(qLower, nameLower) && len(nameLower) >= 4:
			score, ok = 8, true // query contains the full INN (e.g. "cefotaxime injection")
		case strings.Contains(nameLower, qLower) && len(qLower) >= 4:
			score, ok = 6, true // substring
		case e.NameZH != "" && strings.Contains(strings.ToLower(e.NameZH), qLower):
			score, ok = 10, true
		}
		if ok && score >= minEMLScore {
			results = append(results, EMLResult{Entry: *e, Score: score})
		}
	}
	sort.Slice(results, func(i, j int) bool {
		if results[i].Score != results[j].Score {
			return results[i].Score > results[j].Score
		}
		return results[i].Entry.Name < results[j].Entry.Name
	})
	if len(results) > topK {
		results = results[:topK]
	}
	return results, nil
}
