package knowledge

import (
	"context"
	"testing"
)

// TestRetrieverPopSupplement5Recall guards the 2026-09-24 科普补充第五批:
// skin disease home care, eye/ENT screening and acute windows, per-cancer
// early-screening start ages and intervals, and heat stroke / drowning / burn
// injury. Everyday colloquial Chinese questions must recall the new entries in
// top5.
func TestRetrieverPopSupplement5Recall(t *testing.T) {
	r := NewRetriever(newTestStore(t))
	cases := map[string]string{
		// 第五批③：按癌种早筛起始年龄与间隔
		"肺癌筛查做什么检查":         "ces-lung-01",
		"低剂量CT多久做一次":        "ces-lung-01",
		"50岁要做肺癌筛查吗":        "ces-lung-01",
		"胸片能查出肺癌吗":          "ces-lung-01",
		"一天两包烟要查肺癌吗":        "ces-lung-01",
		"体检查出肺结节怎么办":         "ces-lung-02",
		"肺结节多久复查一次":          "ces-lung-02",
		"胃癌筛查多少岁开始":          "ces-gastric-01",
		"幽门螺杆菌阳性要做胃镜吗":      "ces-gastric-01",
		"胃癌几岁开始查":            "ces-gastric-01",
		"萎缩性胃炎多久查一次胃镜":      "ces-gastric-02",
		"肠上皮化生要复查胃镜吗":        "ces-gastric-02",
		"钡餐能筛查胃癌吗":           "ces-gastric-02",
		"肠癌筛查多大年龄开始":         "ces-colorectal-01",
		"肠镜几年做一次":            "ces-colorectal-01",
		"便潜血阳性要紧吗":          "ces-colorectal-01",
		"肠息肉切完多久复查肠镜":        "ces-colorectal-02",
		"溃疡性结肠炎要查肠镜吗":        "ces-colorectal-02",
		"家里好几个人得癌我要早筛吗":     "ces-hereditary-01",
		"林奇综合征怎么筛查":          "ces-hereditary-01",
		"BRCA基因突变什么时候开始筛查":  "ces-hereditary-01",
		"食管癌筛查怎么做":           "ces-esophagus-01",
		"食管癌筛查多少岁停止":         "ces-esophagus-01",
		"长期吃烫的会食管癌吗要查什么":     "ces-esophagus-01",
		"乙肝携带者多久查一次肝癌":       "ces-liver-01",
		"肝癌筛查做什么检查":          "ces-liver-01",
		"超声加AFP能查出肝癌吗":      "ces-liver-01",
		"aMAP评分是什么":          "ces-liver-02",
		"慢性肝病得肝癌风险高吗":        "ces-liver-02",
		"前列腺癌要筛查吗":           "ces-prostate-01",
		"PSA多久查一次":          "ces-prostate-01",
		"甲状腺癌要不要普查":          "ces-thyroid-01",
		"一般人群要查甲状腺癌吗":        "ces-thyroid-01",
		"甲状腺结节TI-RADS4类什么意思": "ces-thyroid-02",
		"甲状腺结节要做穿刺吗":         "ces-thyroid-02",
		"肿瘤标志物能查出癌症吗":        "ces-marker-01",
		"体检肿瘤指标正常说明没癌吗":      "ces-marker-01",
		"哪些检查能真正筛查癌症":        "ces-imaging-01",
		"抽血能查早期癌症吗":          "ces-imaging-01",
		"体检报告写结节息肉要紧吗":       "ces-finding-01",
		"报告上的上皮内瘤变要不要紧":      "ces-finding-01",

		// 第五批④：高温中暑与意外伤害
		"中暑了有什么表现":      "hi-heat-levels",
		"先兆中暑和轻症中暑怎么分": "hi-heat-levels",
		"中暑体温多少度":       "hi-heat-levels",
		"热射病有什么信号":      "hi-heatstroke-signs",
		"热射病死亡率很高吗":     "hi-heatstroke-signs",
		"皮肤干热不出汗是中暑吗":   "hi-heatstroke-signs",
		"有人中暑昏迷了怎么急救":   "hi-heatstroke-firstaid",
		"热射病降温要多久":      "hi-heatstroke-firstaid",
		"高温天腿抽筋是不是中暑":   "hi-heat-cramps-exhaustion",
		"中暑后大量出汗头晕无力":   "hi-heat-cramps-exhaustion",
		"大热天干活怎么喝水":     "hi-heat-hydrate",
		"户外工作多久补一次水":    "hi-heat-hydrate",
		"高温天要补电解质吗":     "hi-heat-hydrate",
		"多少度必须停止室外露天作业": "hi-work-stop-thresholds",
		"高温天气可以停工吗":     "hi-work-stop-thresholds",
		"37度以上能安排加班吗":    "hi-work-stop-thresholds",
		"高温津贴什么温度开始发":   "hi-heat-allowance",
		"哪些人不能高温作业":     "hi-heat-allowance",
		"空调开多少度防暑":      "hi-home-cooling",
		"高温天吹风扇有用吗":     "hi-home-cooling",
		"能把孩子单独留在车里吗":    "hi-home-cooling",
		"高温橙色预警是多少度":    "hi-heat-warnings",
		"高温预警颜色代表什么":    "hi-heat-warnings",
		"哪些人最容易中暑":      "hi-heat-risk-groups",
		"夏天药要不要放冰箱":     "hi-drug-storage-hot",
		"糖浆能放冰箱保存吗":     "hi-drug-storage-hot",
		"阴凉保存是多少度":      "hi-drug-storage-hot",
		"溺水是儿童第一位死因吗":   "hi-drowning-burden",
		"小孩溺水几分钟会致命":    "hi-drowning-burden",
		"孩子在哪里容易溺水":     "hi-drowning-hotspots",
		"小婴儿在浴室溺水":      "hi-drowning-hotspots",
		"防溺水六不是什么":      "hi-drowning-six-nots",
		"同伴掉水里孩子该怎么救":   "hi-drowning-six-nots",
		"看到有人溺水怎么办":     "hi-drowning-rescue",
		"溺水者上岸还要看医生吗":   "hi-drowning-rescue",
		"烫伤了冲脱泡盖送":      "hi-burn-five-steps",
		"被开水烫了怎么处理":     "hi-burn-five-steps",
		"烫伤要冲冷水多久":      "hi-burn-five-steps",
		"烫伤抹牙膏有用吗":      "hi-burn-myths",
		"烫伤能抹酱油吗":       "hi-burn-myths",
		"烫伤起水泡要挑破吗":     "hi-burn-myths",
		"烫伤什么情况要去医院":     "hi-burn-seekcare",
		"小孩烫伤要看医生吗":      "hi-burn-seekcare",
		"暖宝宝低温烫伤":       "hi-lowtemp-burn",
		"热水袋烫一下怎么这么严重":   "hi-lowtemp-burn",
		"低温烫伤多少度会烫":      "hi-lowtemp-burn",
		"家里怎么防止小孩烫伤":     "hi-scald-prevention-home",
		"倒热水要注意什么防烫":     "hi-scald-prevention-home",

		// 第五批①：皮肤病家庭护理与就医时机
		"湿疹能洗澡吗":         "sk-ad-bathe",
		"特应性皮炎洗澡水温多少":    "sk-ad-bathe",
		"湿疹洗澡多久合适":       "sk-ad-bathe",
		"湿疹保湿霜要涂多少":       "sk-ad-moisturize",
		"宝宝湿疹润肤剂用量":       "sk-ad-moisturize",
		"湿疹要天天涂润肤霜吗":      "sk-ad-moisturize",
		"湿疹药膏有激素不敢用":      "sk-ad-steroid",
		"激素药膏分几种":         "sk-ad-steroid",
		"擦激素脸会不会变厚":       "sk-ad-steroid",
		"湿疹好了能马上停药吗":      "sk-ad-maintain",
		"主动维持治疗一周几次":      "sk-ad-maintain",
		"湿包疗法做几天":         "sk-ad-maintain",
		"湿疹要不要忌口":         "sk-ad-diet",
		"牛奶鸡蛋要给宝宝停掉吗":     "sk-ad-diet",
		"银屑病能根治吗":         "sk-psoriasis-cure",
		"牛皮癣能除根吗":         "sk-psoriasis-cure",
		"牛皮癣能洗澡吗":         "sk-psoriasis-care",
		"银屑病洗澡多长时间合适":     "sk-psoriasis-care",
		"银屑病为什么突然加重":       "sk-psoriasis-triggers",
		"同形反应是什么意思":       "sk-psoriasis-triggers",
		"银屑病什么时候算重度":       "sk-psoriasis-severe",
		"牛皮癣多大面积要系统治疗":    "sk-psoriasis-severe",
		"荨麻疹多久算慢性":        "sk-urticaria-6week",
		"风团反复一个多月了":       "sk-urticaria-6week",
		"荨麻疹吃什么药":         "sk-urticaria-meds",
		"抗组胺药要吃多久":        "sk-urticaria-meds",
		"荨麻疹什么时候要去急诊":     "sk-urticaria-emergency",
		"过敏嘴唇肿了呼吸困难":      "sk-urticaria-emergency",
		"痘痘分几级":          "sk-acne-grade",
		"痤疮怎么分级":         "sk-acne-grade",
		"异维A酸要避孕多久":       "sk-acne-isotretinoin",
		"吃治痘痘的药会影响怀孕吗":    "sk-acne-isotretinoin",
		"异维A酸疗程多长":         "sk-acne-isotretinoin",
		"痘痘吃抗生素要吃多久":      "sk-acne-antibiotics",
		"孕妇能用四环素类治痘痘吗":    "sk-acne-antibiotics",
		"痘痘要怎么护肤":        "sk-acne-care",
		"阿达帕林维持治疗多久":      "sk-acne-care",
		"身上环形红斑是癣吗":       "sk-tinea-body",
		"体癣抹药要多久":         "sk-tinea-body",
		"股癣能不能用激素药膏":       "sk-tinea-body",
		"灰指甲要吃药多久":        "sk-tinea-nail",
		"治灰指甲的药伤肝吗":       "sk-tinea-nail",
		"发际线后移是什么脱发":      "sk-hair-aga",
		"雄激素性脱发能治吗":       "sk-hair-aga",
		"脱发怎么用药":         "sk-hair-drugs",
		"米诺地尔男的女的用哪种浓度":   "sk-hair-drugs",
		"非那雄胺用量是多少":       "sk-hair-drugs",
		"斑秃能自愈吗":         "sk-hair-aa",
		"一块块掉头发怎么回事":      "sk-hair-aa",
		"带状疱疹好了还疼":       "sk-hz-pain",
		"蛇盘疮后遗症神经痛":      "sk-hz-pain",
		"后遗神经痛多大年纪容易得":    "sk-hz-pain",
		"防晒霜SPF多少合适":     "sk-sun-spf",
		"防晒衣UPF50是什么意思": "sk-sun-spf",
		"紫外线指数多少要防晒":     "sk-sun-spf",
		"PA加号越多越好吗":      "sk-sun-spf",
		"几点到几点不要晒太阳":     "sk-sun-habits",
		"防晒霜多久补涂一次":      "sk-sun-habits",
		"几个月宝宝能用防晒霜":     "sk-sun-habits",

		// 第五批②：眼耳鼻喉
		"眼睛干涩是怎么回事":       "ee-dryeye-cause",
		"看屏幕久了眼睛干":         "ee-dryeye-cause",
		"戴隐形眼镜眼睛干":         "ee-dryeye-cause",
		"人工泪液能长期滴吗":       "ee-dryeye-tears",
		"眼药水一天用几次要换不含防腐剂的": "ee-dryeye-tears",
		"眼睛干热敷还是冷敷":        "ee-dryeye-compress",
		"睑板腺按摩怎么做":         "ee-dryeye-compress",
		"干眼症怎么查出来":         "ee-dryeye-check",
		"泪膜破裂时间是什么":        "ee-dryeye-check",
		"红眼病怎么传染":          "ee-redeye-spread",
		"红眼病看一眼会被传染吗":      "ee-redeye-spread",
		"红眼病要隔离吗":          "ee-redeye-spread",
		"红眼病能包扎眼睛吗":        "ee-redeye-care",
		"红眼病要用抗生素吗":        "ee-redeye-care",
		"红眼病多久能好要不要继续治疗":   "ee-redeye-care",
		"麦粒肿和霰粒肿区别":        "ee-stye-chalazion",
		"眼睛长针眼能挤吗":         "ee-stye-chalazion",
		"小孩多大开始查视力":        "ee-childvision-schedule",
		"儿童视力筛查几次":         "ee-childvision-schedule",
		"4岁孩子视力多少算正常":      "ee-childvision-schedule",
		"孩子远视储备不足怎么办":      "ee-childvision-referral",
		"屈光筛查异常要配镜吗":       "ee-childvision-referral",
		"婴儿瞳孔发白要紧吗":        "ee-childvision-redflag",
		"小孩眼睛哪些信号要马上就医":    "ee-childvision-redflag",
		"突然耳朵听不见了怎么办":      "ee-sudden-deaf-window",
		"突发性聋多久内要看医生":      "ee-sudden-deaf-window",
		"突发性聋用什么药":         "ee-sudden-deaf-treat",
		"耳朵突然聋了能用激素吗":      "ee-sudden-deaf-treat",
		"激素吃药没用还能打鼓室针吗":    "ee-sudden-deaf-treat",
		"流鼻血怎么止血":          "ee-epistaxis-stop",
		"鼻出血要捏鼻子多久":        "ee-epistaxis-stop",
		"流鼻血能不能仰头":         "ee-epistaxis-stop",
		"鼻血止不住要上医院吗":       "ee-epistaxis-visit",
		"小孩睡觉打呼张嘴呼吸":       "ee-kidsnoring-osa",
		"孩子打鼾是病吗":          "ee-kidsnoring-osa",
		"腺样体手术什么条件能做":      "ee-adenoid-surgery",
		"扁桃体腺样体日间手术年龄要求":   "ee-adenoid-surgery",
		"小孩手术前多久不能吃东西":     "ee-adenoid-fasting",
		"术前禁食几小时":          "ee-adenoid-fasting",
		"喝过奶手术前要等多久":        "ee-adenoid-fasting",
		"扁桃体手术后可以吃什么":       "ee-adenoid-postop",
		"腺样体术后什么时候最疼":       "ee-adenoid-postop",
		"洗鼻子用什么盐水":         "ee-nasal-irrigation",
		"小孩能洗鼻子吗":          "ee-nasal-irrigation",
		"鼻塞流鼻涕多久是鼻窦炎":      "ee-sinusitis-visit",
		"鼻窦炎多久要手术":         "ee-sinusitis-visit",
	}
	for query, want := range cases {
		res, err := r.Retrieve(context.Background(), query, 5)
		if err != nil {
			t.Fatal(err)
		}
		found := false
		for _, rr := range res {
			if rr.Entry.ID == want {
				found = true
				break
			}
		}
		if !found {
			got := make([]string, 0, len(res))
			for _, rr := range res {
				got = append(got, rr.Entry.ID)
			}
			t.Errorf("查询 %q: 期望 top5 含 %s, 实际 %v", query, want, got)
		}
	}
}
