package knowledge

import (
	"context"
	"testing"
)

// TestRetrieverBatch19YiigleRecall guards the 2026-10-01 科普扩充第十九批(第二波):
//
//	yiigle_guides_wave4.json yg4- 49 条 ← 中华医学会临床指南第四轮 43 篇全文
//	(儿科与小儿外科 / 妇产与围产 / 慢病与急症 / 感染 / 皮肤五组；正文一律写入
//	prevention、when_to_seek_care、risk_factors、complications、treatment 这些
//	KnowledgeEntry 真正会加载的字段，不用会被 loader 丢弃的 summary_zh/details_zh)
//
// Each case is a natural spoken question (never the condition_zh verbatim) that
// must land the target entry inside the top5. Recall failures are fixed in the
// data layer only — keywords on the entry that lost, or assertion ownership when
// the new entry is the better answer — never by moving a threshold or editing
// retriever_keyword.go.
func TestRetrieverBatch19YiigleRecall(t *testing.T) {
	r := NewRetriever(newTestStore(t))
	cases := map[string]string{
		// ---------- g1 ----------
		"怀孕前要不要查地中海贫血":        "yg4-thal-prepreg-screen",
		"夫妻两个都是地贫携带者怎么办":      "yg4-thal-prepreg-screen",
		"地贫基因检测什么时候做":         "yg4-thal-prepreg-screen",
		"血常规怎么看是不是地贫携带者":      "yg4-thal-prepreg-screen",
		"无创DNA能不能查出地中海贫血":     "yg4-thal-prepreg-screen",
		"南方人为什么婚检要查地贫":        "yg4-thal-prepreg-screen",
		"地中海贫血孕妇贫血加重怎么办":      "yg4-thal-preg-manage",
		"怀孕有地贫要不要输血":          "yg4-thal-preg-manage",
		"地贫孕妇叶酸吃多少":           "yg4-thal-preg-manage",
		"备孕在吃去铁胺还能怀孕吗":        "yg4-thal-preg-manage",
		"地贫孕妇多久复查一次血常规":       "yg4-thal-preg-manage",
		"重型地贫孕妇生孩子危险吗":        "yg4-thal-preg-manage",
		"B超说宝宝偏小是不是胎儿发育迟缓":    "yg4-fgr-diagnose",
		"胎儿生长受限是什么意思":         "yg4-fgr-diagnose",
		"胎儿腹围偏小要紧吗":           "yg4-fgr-diagnose",
		"小于胎龄儿和胎儿生长受限一样吗":     "yg4-fgr-diagnose",
		"多久做一次B超监测胎儿生长":       "yg4-fgr-diagnose",
		"脐动脉血流异常说明什么":         "yg4-fgr-diagnose",
		"宝宝生长受限要不要提前生":        "yg4-fgr-manage",
		"胎儿偏小什么时候终止妊娠":        "yg4-fgr-manage",
		"脐动脉血流缺失还能等吗":         "yg4-fgr-manage",
		"胎儿生长受限能顺产吗":          "yg4-fgr-manage",
		"怀孕吸氧能长胎吗":            "yg4-fgr-manage",
		"阿司匹林能预防宝宝偏小吗":        "yg4-fgr-manage",
		"宝宝生长曲线怎么看":           "yg4-child-growth-eval",
		"宝宝体重长期不增是生长异常吗":      "yg4-child-growth-eval",
		"多久给婴儿量一次身高体重":        "yg4-child-growth-eval",
		"头围要量到几岁":             "yg4-child-growth-eval",
		"宝宝体重一直不增加怎么办":        "yg4-child-growth-eval",
		"生长曲线跨了两条百分位线要紧吗":     "yg4-child-growth-eval",
		"耳聋基因筛查有必要做吗":         "yg4-hearing-gene-screen",
		"新生儿耳聋基因筛查没通过怎么办":     "yg4-hearing-gene-screen",
		"夫妻双方都携带耳聋基因能生育吗":     "yg4-hearing-gene-screen",
		"耳聋基因筛查查哪几个基因":        "yg4-hearing-gene-screen",
		"携带耳聋基因会不会遗传给孩子":      "yg4-hearing-gene-screen",
		"为什么带线粒体基因变异不能随便用抗生素": "yg4-hearing-gene-screen",
		"新生儿听力筛查没通过是不是聋了":     "yg4-infant-hearing-intervene",
		"42天听力复筛还没过怎么办":       "yg4-infant-hearing-intervene",
		"宝宝几个月能确诊听力损失":        "yg4-infant-hearing-intervene",
		"听力损失多久内要干预":          "yg4-infant-hearing-intervene",
		"宝宝听力不好要做耳聋基因检测吗":     "yg4-infant-hearing-intervene",
		"人工耳蜗几岁做合适":           "yg4-infant-hearing-intervene",
		"闻不到气味是什么原因":          "yg4-hyposmia-treat",
		"嗅觉减退怎么检查":            "yg4-hyposmia-treat",
		"感冒后闻不到味道能恢复吗":        "yg4-hyposmia-treat",
		"嗅觉训练怎么做":             "yg4-hyposmia-treat",
		"失去嗅觉能治好吗":            "yg4-hyposmia-treat",
		"老年人嗅觉下降要警惕什么病":       "yg4-hyposmia-treat",
		// ---------- g2 ----------
		"新生儿一侧睾丸摸不到怎么办":     "yg4-cryptorchidism",
		"宝宝蛋蛋没下来要不要紧":       "yg4-cryptorchidism",
		"隐睾什么时候做手术最好":       "yg4-cryptorchidism",
		"回缩性睾丸和隐睾的区别":       "yg4-cryptorchidism",
		"隐睾一定要手术吗":          "yg4-cryptorchidism",
		"隐睾术后还会复发吗":         "yg4-cryptorchidism",
		"新生儿黄疸一直不退怎么办":      "yg4-biliary-atresia",
		"宝宝大便发白是不是肝胆有问题":    "yg4-biliary-atresia",
		"胆道闭锁能早期发现吗":        "yg4-biliary-atresia",
		"胆道闭锁手术最佳时间":        "yg4-biliary-atresia",
		"白陶土色大便是怎么回事":       "yg4-biliary-atresia",
		"胆道闭锁不做手术会怎么样":      "yg4-biliary-atresia",
		"新生儿髋关节筛查什么时候做":     "yg4-ddh-screen",
		"宝宝臀纹不对称要紧吗":        "yg4-ddh-screen",
		"髋关节发育不良能自愈吗":       "yg4-ddh-screen",
		"婴儿髋关节超声有必要做吗":      "yg4-ddh-screen",
		"女宝宝髋关节外展受限怎么办":     "yg4-ddh-screen",
		"六个月宝宝髋关节发育不良怎么治疗":  "yg4-ddh-screen",
		"五岁还尿床是不是病":         "yg4-child-enuresis",
		"孩子尿床需要看医生吗":        "yg4-child-enuresis",
		"儿童遗尿症怎么治疗":         "yg4-child-enuresis",
		"尿床报警器有用吗":          "yg4-child-enuresis",
		"去氨加压素治尿床安全吗":       "yg4-child-enuresis",
		"大人叫醒尿床的孩子有用吗":      "yg4-child-enuresis",
		"小儿肺炎怎么判断严重程度":      "yg4-child-cap",
		"小儿肺炎什么情况下要住院":      "yg4-child-cap",
		"孩子持续发热咳嗽超过几天要警惕肺炎": "yg4-child-cap",
		"怎么判断是不是重症肺炎":       "yg4-child-cap",
		"婴儿肺炎有哪些早期表现":       "yg4-child-cap",
		"肺炎呼吸增快多少算快":        "yg4-child-cap",
		"孩子支原体抗体阳性就是感染了吗":   "yg4-mycoplasma-pediatric",
		"支原体肺炎多久能转阴":        "yg4-mycoplasma-pediatric",
		"支原体核酸阳性代表感染吗":      "yg4-mycoplasma-pediatric",
		"支原体肺炎吃阿奇霉素没用怎么办":   "yg4-mycoplasma-pediatric",
		"支原体抗体滴度多少算感染":      "yg4-mycoplasma-pediatric",
		"支原体肺炎阿奇霉素要吃几个疗程":   "yg4-mycoplasma-pediatric",
		"宝宝吃花生呛到一直咳怎么办":     "yg4-child-airway-fb",
		"孩子呛咳后憋气要不要去医院":     "yg4-child-airway-fb",
		"气管支气管异物怎么取出来":      "yg4-child-airway-fb",
		"气管异物多久之内要做手术":      "yg4-child-airway-fb",
		"孩子反复肺炎会不会是气管异物":    "yg4-child-airway-fb",
		"支气管镜取异物安全吗":        "yg4-child-airway-fb",
		// ---------- g3 ----------
		"孩子腿上出紫癜关节还疼是怎么回事":    "yg4-child-hsp",
		"过敏性紫癜要不要查尿常规":        "yg4-child-hsp",
		"过敏性紫癜肚子疼得厉害要紧吗":      "yg4-child-hsp",
		"小孩下肢对称的红出血点压不褪色":     "yg4-child-hsp",
		"过敏性紫癜要随访多久":          "yg4-child-hsp",
		"紫癜性肾炎早期有什么表现":        "yg4-child-hsp",
		"孩子反复肚子痛还便血会不会是炎症性肠病": "yg4-child-ibd",
		"儿童炎症性肠病早期症状有哪些":      "yg4-child-ibd",
		"小孩拉肚子带血体重不长了":        "yg4-child-ibd",
		"儿童炎症性肠病要做肠镜吗":        "yg4-child-ibd",
		"孩子克罗恩病影响长个子吗":        "yg4-child-ibd",
		"儿童溃疡性肠病一定要吃药吗":       "yg4-child-ibd",
		"孩子老喝水老上厕所还瘦了是不是糖尿病":  "yg4-child-t1dm",
		"1型糖尿病和2型糖尿病怎么区分":     "yg4-child-t1dm",
		"儿童1型糖尿病要打胰岛素吗":       "yg4-child-t1dm",
		"1型糖尿病孩子呕吐呼吸急促是酮症吗":   "yg4-child-t1dm",
		"1型糖尿病一天要测几次血糖":       "yg4-child-t1dm",
		"1型糖尿病多久查一次糖化血红蛋白":    "yg4-child-t1dm",
		"糖耐量筛查是几周做的":          "yg4-gdm-screen",
		"妊娠期糖尿病的诊断标准是什么":      "yg4-gdm-screen",
		"糖耐量有一项偏高就是妊娠糖尿病吗":    "yg4-gdm-screen",
		"查出妊娠期糖尿病控制饮食还要运动吗":   "yg4-gdm-screen",
		"妊娠期糖尿病什么时候要打胰岛素":     "yg4-gdm-screen",
		"妊娠期糖尿病生完孩子还要复查吗":     "yg4-gdm-screen",
		"有规律宫缩多久该去医院生":        "yg4-normal-labor",
		"宫口开到几厘米才算进入活跃期":      "yg4-normal-labor",
		"产程中可以先喝水吃点东西吗":       "yg4-normal-labor",
		"生的时候能不能站着或蹲着生":       "yg4-normal-labor",
		"无痛分娩会不会增加剖宫产率":       "yg4-normal-labor",
		"顺产后为什么要留产房观察两小时":     "yg4-normal-labor",
		"怀孕晚期突然出血不疼是怎么回事":     "yg4-placenta-previa",
		"B超说胎盘位置低要不要紧":        "yg4-placenta-previa",
		"前置胎盘什么时候做剖宫产":        "yg4-placenta-previa",
		"胎盘低置可以顺产吗":           "yg4-placenta-previa",
		"前置胎盘必须提前住院吗":         "yg4-placenta-previa",
		"做过剖宫产再次怀孕容易前置胎盘吗":    "yg4-placenta-previa",
		"下面突然流水控制不住是不是破水了":    "yg4-pprom",
		"怎么判断是不是胎膜早破":         "yg4-pprom",
		"怀疑破水了能不能在家观察":        "yg4-pprom",
		"胎膜早破是不是一直要躺着":        "yg4-pprom",
		"破水后发烧肚子压痛是感染了吗":      "yg4-pprom",
		"足月破水多久还不生要引产":        "yg4-pprom",
		"鼻咽癌分期是怎么划分的":         "yg4-npc-staging",
		"鼻咽癌分期有什么用":           "yg4-npc-staging",
		"鼻咽癌第8版分期和2008版有什么不同": "yg4-npc-staging",
		"鼻咽癌T1T2T3怎么区分":       "yg4-npc-staging",
		"鼻咽癌几期算严重":            "yg4-npc-staging",
		"鼻咽癌分期要不要做PET-CT":     "yg4-npc-staging",
		// ---------- g4 ----------
		"小腹一直疼还发烧是不是盆腔炎":     "yg4-pid",
		"盆腔炎要不要住院":           "yg4-pid",
		"盆腔炎要用多久抗生素才能停":      "yg4-pid",
		"盆腔炎输液好转后能改成吃药吗":     "yg4-pid",
		"盆腔炎治好了还要复查吗":        "yg4-pid",
		"盆腔炎会不会导致不孕":         "yg4-pid",
		"白带有鱼腥臭味是细菌性阴道病吗":    "yg4-bacterial-vaginosis",
		"细菌性阴道病怎么确诊":         "yg4-bacterial-vaginosis",
		"细菌性阴道病老是复发怎么办":      "yg4-bacterial-vaginosis",
		"甲硝唑治细菌性阴道病要吃几天":     "yg4-bacterial-vaginosis",
		"怀孕查出细菌性阴道病要不要治":     "yg4-bacterial-vaginosis",
		"哺乳期细菌性阴道病怎么用药":      "yg4-bacterial-vaginosis",
		"阴道炎反反复复是不是几种炎症混在一起": "yg4-mixed-vaginitis",
		"能不能一次查清楚有哪几种阴道炎":    "yg4-mixed-vaginitis",
		"霉菌和细菌一起感染了用什么药":     "yg4-mixed-vaginitis",
		"混合性阴道炎是不是要治更久":      "yg4-mixed-vaginitis",
		"滴虫阳性伴侣要不要一起治":       "yg4-mixed-vaginitis",
		"阴道炎总是治不好怎么办":        "yg4-mixed-vaginitis",
		"痛经一年比一年加重是子宫内膜异位吗":  "yg4-endometriosis",
		"巧克力囊肿要不要做手术":        "yg4-endometriosis",
		"子宫内膜异位症怎么确诊":        "yg4-endometriosis",
		"内异症手术后还会长回来吗":       "yg4-endometriosis",
		"子宫内膜异位导致怀不上怎么办":     "yg4-endometriosis",
		"内异症术后吃药要维持多久":       "yg4-endometriosis",
		"下面有东西脱出来是盆腔器官脱垂吗":   "yg4-pelvic-organ-prolapse",
		"久站后下面有下坠感是不是脱垂":     "yg4-pelvic-organ-prolapse",
		"子宫脱垂和阴道壁膨出是一回事吗":    "yg4-pelvic-organ-prolapse",
		"凯格尔运动能改善脱垂吗":        "yg4-pelvic-organ-prolapse",
		"脱垂一定要做手术吗":          "yg4-pelvic-organ-prolapse",
		"子宫托适合什么样的人用":        "yg4-pelvic-organ-prolapse",
		"高危行为后多久查梅毒才查得出来":    "yg4-syphilis-treat",
		"梅毒滴度1比2需要治疗吗":       "yg4-syphilis-treat",
		"梅毒治好后要复查几年":         "yg4-syphilis-treat",
		"梅毒抗体阳性会不会转阴":        "yg4-syphilis-treat",
		"怀孕了查出梅毒会不会传给孩子":     "yg4-syphilis-treat",
		"对青霉素过敏的梅毒怎么治":       "yg4-syphilis-treat",
		"宫颈分泌物查出沙眼衣原体阳性怎么治":  "yg4-gonorrhea-chlamydia-treat",
		"淋球菌阳性需要夫妻一起治疗吗":     "yg4-gonorrhea-chlamydia-treat",
		"衣原体感染治疗后什么时候复查":     "yg4-gonorrhea-chlamydia-treat",
		"白带脓性还发热会不会是淋球菌感染":   "yg4-gonorrhea-chlamydia-treat",
		"轻微下腹痛一直低热查得出衣原体吗":   "yg4-gonorrhea-chlamydia-treat",
		"治支原体衣原体期间能同房吗":      "yg4-gonorrhea-chlamydia-treat",
		"多囊卵巢综合征怎么怀孕":        "yg4-pcos-endocrine",
		"月经几个月来一次是不是多囊":      "yg4-pcos-endocrine",
		"多囊备孕要先减重吗":          "yg4-pcos-endocrine",
		"雄激素高又月经不调是多囊吗":      "yg4-pcos-endocrine",
		"确诊多囊每年都要查血糖吗":       "yg4-pcos-endocrine",
		"二甲双胍对备孕的多囊有用吗":      "yg4-pcos-endocrine",
		// ---------- g5 ----------
		"老年人血糖控制目标怎么定":         "yg4-elderly-dm-target",
		"老年人血糖控制目标定在多少合适":      "yg4-elderly-dm-target",
		"老年人低血糖会有什么表现":         "yg4-elderly-dm-target",
		"老人夜里低血糖有什么征兆":         "yg4-elderly-dm-target",
		"老年糖尿病血糖要不要控得太严":       "yg4-elderly-dm-target",
		"健康状态差的老人血糖标准能放宽吗":     "yg4-elderly-dm-target",
		"老年糖尿病首选什么降糖药":         "yg4-elderly-dm-meds",
		"老年人糖尿病吃二甲双胍肾功能不好还能吃吗": "yg4-elderly-dm-meds",
		"肾功能不全的老人选哪种降糖药":       "yg4-elderly-dm-meds",
		"老人吃磺脲类药物为什么容易低血糖":     "yg4-elderly-dm-meds",
		"利格列汀需要根据肾功能调整剂量吗":     "yg4-elderly-dm-meds",
		"老年糖尿病患者同时吃很多药要注意什么":   "yg4-elderly-dm-meds",
		"活动后气促是不是肺动脉高压":        "yg4-pah-diagnose",
		"肺动脉高压怎么确诊":            "yg4-pah-diagnose",
		"右心导管检查是查什么的":          "yg4-pah-diagnose",
		"肺动脉高压需要做哪些检查":         "yg4-pah-diagnose",
		"喘不上气还腿肿是肺动脉高压吗":       "yg4-pah-diagnose",
		"心电图正常能排除肺动脉高压吗":       "yg4-pah-diagnose",
		"中风溶栓时间窗是多久":           "yg4-stroke-thrombolysis-window",
		"脑梗多久之内可以溶栓":           "yg4-stroke-thrombolysis-window",
		"发病超过3小时还能溶栓吗":         "yg4-stroke-thrombolysis-window",
		"卒中到院后先做颅脑影像检查吗":       "yg4-stroke-thrombolysis-window",
		"取栓的时间窗一般是几小时":         "yg4-stroke-thrombolysis-window",
		"哪些中风病人不能打溶栓针":         "yg4-stroke-thrombolysis-window",
		"中风后二级预防要吃什么药":         "yg4-stroke-secondary-prevention",
		"脑梗复发预防要长期吃阿司匹林吗":      "yg4-stroke-secondary-prevention",
		"轻度脑梗双联抗血小板吃多少天":       "yg4-stroke-secondary-prevention",
		"房颤引起的中风后什么时候开始抗凝":     "yg4-stroke-secondary-prevention",
		"卒中后他汀要把低密度脂蛋白降到多少":    "yg4-stroke-secondary-prevention",
		"吃着阿司匹林又中风了怎么办":        "yg4-stroke-secondary-prevention",
		"胸痛持续半小时以上是不是心梗":       "yg4-stemi-reperfusion",
		"心梗多久内放支架最好":           "yg4-stemi-reperfusion",
		"急性心梗来不及做PCI怎么办":       "yg4-stemi-reperfusion",
		"胸痛中心为什么能救命":           "yg4-stemi-reperfusion",
		"心梗出院后双联抗血小板要吃多久":      "yg4-stemi-reperfusion",
		"第一次心电图正常还要复查吗":        "yg4-stemi-reperfusion",
		"系统性红斑狼疮怎么治疗":          "yg4-sle-treat",
		"狼疮为什么要长期吃羟氯喹":         "yg4-sle-treat",
		"红斑狼疮激素能不能少吃一点":        "yg4-sle-treat",
		"狼疮患者尿里泡沫多是不是伤肾了":      "yg4-sle-treat",
		"红斑狼疮什么时候可以考虑怀孕":       "yg4-sle-treat",
		"狼疮复查多久评估一次病情":         "yg4-sle-treat",
		"高血压药五大类怎么选":           "yg4-htn-drug-choice",
		"地平类和普利类降压药哪个副作用小":     "yg4-htn-drug-choice",
		"两种降压药一起吃好还是买复方":       "yg4-htn-drug-choice",
		"吃普利类降压药干咳怎么办":         "yg4-htn-drug-choice",
		"吃地平类降压药脚踝水肿正常吗":       "yg4-htn-drug-choice",
		"吃氢氯噻嗪要不要补钾":           "yg4-htn-drug-choice",
		// ---------- g6 ----------
		"误食毒物后第一时间该做什么":     "yg4-acute-poisoning-home",
		"吃错药了要不要自己催吐":       "yg4-acute-poisoning-home",
		"误服药物中毒多久内洗胃有效":     "yg4-acute-poisoning-home",
		"误食后要把剩余药物带去医院吗":    "yg4-acute-poisoning-home",
		"皮肤溅到农药怎么紧急处理":      "yg4-acute-poisoning-home",
		"怀疑误食有毒东西要不要看急诊":    "yg4-acute-poisoning-home",
		"有机磷农药中毒用什么解毒药":     "yg4-acute-poisoning-antidote",
		"解磷定是治什么中毒的":        "yg4-acute-poisoning-antidote",
		"阿片类药物过量用什么解救":      "yg4-acute-poisoning-antidote",
		"安眠药中毒有特效解毒剂吗":      "yg4-acute-poisoning-antidote",
		"退烧药吃过量肝脏解毒用什么药":    "yg4-acute-poisoning-antidote",
		"中毒是不是都有对应的解毒药":     "yg4-acute-poisoning-antidote",
		"腹股沟和臀部疼是不是股骨头坏死":   "yg4-onfh-staging",
		"吃激素以后大腿根疼要拍核磁吗":    "yg4-onfh-staging",
		"走路跛行髋部疼是怎么回事":      "yg4-onfh-staging",
		"股骨头坏死早期X线能看出来吗":    "yg4-onfh-staging",
		"长期喝酒会引起股骨头坏死吗":     "yg4-onfh-staging",
		"股骨头塌陷了还能保髋吗":       "yg4-onfh-staging",
		"大腿根鼓个包躺下就没了是不是疝气":  "yg4-inguinal-hernia",
		"腹股沟疝一定要开刀吗":        "yg4-inguinal-hernia",
		"疝块推不回去还疼要不要马上去医院":  "yg4-inguinal-hernia",
		"不想手术能不能用疝气带顶着":     "yg4-inguinal-hernia",
		"疝气手术后还会复发吗":        "yg4-inguinal-hernia",
		"老年女性疝气为什么要尽早手术":    "yg4-inguinal-hernia",
		"尿路感染老是反复怎么办":       "yg4-uti-treat",
		"尿频尿急吃药几天能停药":       "yg4-uti-treat",
		"一年得三次尿路感染要长期吃药预防吗": "yg4-uti-treat",
		"怎么预防尿路感染复发":        "yg4-uti-treat",
		"怀孕尿培养有细菌但没有症状要治吗":  "yg4-uti-treat",
		"肾盂肾炎抗生素要用两周吗":      "yg4-uti-treat",
		// ---------- g7 ----------
		"手部湿疹反复发作怎么办":         "yg4-hand-eczema",
		"手部湿疹反复干裂脱皮怎么治":       "yg4-hand-eczema",
		"手部湿疹反复起水疱是汗疱疹吗":      "yg4-hand-eczema",
		"手部湿疹用什么药膏好":          "yg4-hand-eczema",
		"手部湿疹要不要查过敏原":         "yg4-hand-eczema",
		"经常湿手作业手部湿疹反复":        "yg4-hand-eczema",
		"痒了两个月算慢性瘙痒吗":         "yg4-chronic-pruritus",
		"慢性瘙痒要查什么病":           "yg4-chronic-pruritus",
		"慢性瘙痒怎么治":             "yg4-chronic-pruritus",
		"老年人慢性瘙痒怎么回事":         "yg4-chronic-pruritus",
		"慢性瘙痒查不出原因怎么办":        "yg4-chronic-pruritus",
		"慢性瘙痒是药物引起的吗":         "yg4-chronic-pruritus",
		"白癜风能治好吗能复色吗":         "yg4-vitiligo-treat",
		"白癜风复色要多久":            "yg4-vitiligo-treat",
		"白癜风用他克莫司要涂几个月":       "yg4-vitiligo-treat",
		"白癜风怎么判断是进展期还是稳定期":    "yg4-vitiligo-treat",
		"皮肤损伤后长白斑是白癜风同形反应吗":   "yg4-vitiligo-treat",
		"白癜风能晒太阳吗":            "yg4-vitiligo-treat",
		"家里人多次得肠癌是遗传性结直肠癌吗":   "yg4-lynch-crcc",
		"遗传性结直肠癌几岁开始做肠镜":      "yg4-lynch-crcc",
		"有遗传性结直肠癌家族史要筛查吗":     "yg4-lynch-crcc",
		"遗传性结直肠癌基因检测怎么做":      "yg4-lynch-crcc",
		"家族性腺瘤性息肉病属于遗传性结直肠癌吗": "yg4-lynch-crcc",
		"遗传性结直肠癌做完手术还要复查吗":    "yg4-lynch-crcc",
		"皮肤清洁一天做几次合适":         "yg4-skin-hygiene-care",
		"面部皮肤清洁用什么好":          "yg4-skin-hygiene-care",
		"皮肤清洁过度会不会破坏皮脂膜":      "yg4-skin-hygiene-care",
		"洗脸水温和次数怎么定":          "yg4-skin-hygiene-care",
		"皮肤清洁只用清水可以吗":         "yg4-skin-hygiene-care",
		"老年人皮肤干燥怎么清洁":         "yg4-skin-hygiene-care",
	}
	ctx := context.Background()
	for query, want := range cases {
		res, err := r.Retrieve(ctx, query, 5)
		if err != nil {
			t.Fatalf("查询 %q 检索失败: %v", query, err)
		}
		found := false
		for _, item := range res {
			if item.Entry.ID == want {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("查询 %q: 期望 top5 含 %s，实际 %v", query, want, entryIDs(res))
		}
	}
}
