package safety

import "strings"

// DisclaimerZH is the standard medical disclaimer in Chinese.
const DisclaimerZH = `---

> ⚠️ **医学免责声明**
>
> 本回答由AI医疗助手生成，**仅供医学教育和信息参考**，不能替代执业医师的专业诊断、治疗建议或处方。
>
> - 如果您遇到**紧急医疗情况**，请立即拨打 **120**（中国大陆急救电话）
> - 任何用药、检查或治疗方案应在**医生指导下**进行
> - 本回答引用的医学文献和指南可能存在时效性，请以最新版本为准
> - 如果您有持续或加重的症状，请**尽早就医**
`

// DisclaimerEN is the standard medical disclaimer in English.
const DisclaimerEN = `---

> ⚠️ **Medical Disclaimer**
>
> This response is generated by an AI medical assistant for **educational and informational purposes only**. It does not replace professional medical diagnosis, treatment advice, or prescriptions from a licensed physician.
>
> - In case of a **medical emergency**, call your local emergency number immediately (120 in China, 911 in the US)
> - Any medication, testing, or treatment decisions should be made **under the guidance of a physician**
> - Cited medical literature and guidelines may have been superseded by more recent publications
> - If your symptoms persist or worsen, **seek medical attention promptly**
`

// DisclaimerService manages disclaimer insertion into agent responses.
type DisclaimerService struct {
	// Track whether disclaimer has been shown in the current conversation
	sessionsShown map[string]bool
}

// NewDisclaimerService creates a new disclaimer service.
func NewDisclaimerService() *DisclaimerService {
	return &DisclaimerService{
		sessionsShown: make(map[string]bool),
	}
}

// Apply appends the disclaimer to a response if it hasn't been shown
// in this conversation session yet.
func (d *DisclaimerService) Apply(sessionID, response string) string {
	shown, ok := d.sessionsShown[sessionID]
	if ok && shown {
		return response
	}

	// Check if the response already contains a disclaimer
	if strings.Contains(response, "医学免责声明") || strings.Contains(response, "Medical Disclaimer") {
		d.sessionsShown[sessionID] = true
		return response
	}

	d.sessionsShown[sessionID] = true
	return response + "\n" + DisclaimerZH
}

// ForceApply always appends the disclaimer, regardless of session state.
// Use for non-session or stateless contexts.
func ForceApply(response string) string {
	return response + "\n" + DisclaimerZH
}

// Reset clears the session disclaimer state.
func (d *DisclaimerService) Reset(sessionID string) {
	delete(d.sessionsShown, sessionID)
}
